[package]
name = "yt-dlp-desktop"
version = "1.0.0"
description = "yt-dlp Desktop GUI"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
tauri = { version = "=2.11.5", features = [] }
tauri-plugin-shell = "=2.3.5"
tauri-plugin-dialog = "=2.7.2"
tauri-plugin-fs = "=2.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0"

[lib]
name = "yt_dlp_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
